name: Rails Rspec Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      RUBY_VERSION: 2.6.3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    # Install the necessary MySQL dev packages
    - name: 'Install Mysql Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Install Bundler'
      run: |
        gem install bundler -v '1.17.2'
        bundle config path vendor/bundle

    # Try to retrieve the gems from the cache
    - name: 'Cache Gems'
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: 'Run Bundler'
      run: bundle install --jobs 4 --retry 3

    # Startup MySQL
    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Setup Test DB'
      run: bundle exec rake db:setup

    - name: 'Configure Application'
      run: ./travis-prep.sh

    - name: Build and test with Rake
      run: bundle exec rake
